import oracledb

# ============================================================
# Script de inicialización completa de la BD del Mundial 2026
# Ejecutar: python init_db.py
# ============================================================

DSN  = "localhost/xe"
USER = "SYSTEM"
PWD  = "ORLO"

# Orden correcto para borrar sin violar FK
DROP_ORDER = [
    "Participacion", "Director_Tecnico", "Jugador", "Persona",
    "Partido", "Bitacora", "Seleccion", "Grupo",
    "Estadio", "Usuario", "Posicion", "Confederacion", "Ciudad"
]

CREATIONS = [
    """CREATE TABLE Ciudad (
        codigo NUMBER PRIMARY KEY,
        nombre VARCHAR2(100) NOT NULL,
        pais   VARCHAR2(100) NOT NULL
    )""",
    """CREATE TABLE Confederacion (
        codigo NUMBER PRIMARY KEY,
        nombre VARCHAR2(100) NOT NULL
    )""",
    """CREATE TABLE Posicion (
        codigo NUMBER PRIMARY KEY,
        nombre VARCHAR2(50) NOT NULL
    )""",
    """CREATE TABLE Usuario (
        codigo         NUMBER PRIMARY KEY,
        nombre_usuario VARCHAR2(50)  NOT NULL UNIQUE,
        contrasena     VARCHAR2(100) NOT NULL,
        tipo_usuario   VARCHAR2(20)  NOT NULL,
        CONSTRAINT ck_tipo_usuario CHECK (tipo_usuario IN ('ADMINISTRADOR','TRADICIONAL','ESPORADICO'))
    )""",
    """CREATE TABLE Estadio (
        codigo     NUMBER PRIMARY KEY,
        nombre     VARCHAR2(100) NOT NULL,
        capacidad  NUMBER        NOT NULL,
        cod_ciudad NUMBER        NOT NULL,
        FOREIGN KEY (cod_ciudad) REFERENCES Ciudad(codigo)
    )""",
    """CREATE TABLE Grupo (
        codigo NUMBER PRIMARY KEY,
        letra  VARCHAR2(1) NOT NULL UNIQUE
    )""",
    """CREATE TABLE Seleccion (
        codigo            NUMBER PRIMARY KEY,
        nombre            VARCHAR2(100) NOT NULL,
        descripcion       VARCHAR2(255),
        escudo            BLOB,
        cod_confederacion NUMBER NOT NULL,
        cod_grupo         NUMBER,
        FOREIGN KEY (cod_confederacion) REFERENCES Confederacion(codigo),
        FOREIGN KEY (cod_grupo)         REFERENCES Grupo(codigo)
    )""",
    """CREATE TABLE Bitacora (
        id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        cod_usuario   NUMBER    NOT NULL,
        fecha_entrada TIMESTAMP NOT NULL,
        fecha_salida  TIMESTAMP,
        FOREIGN KEY (cod_usuario) REFERENCES Usuario(codigo)
    )""",
    """CREATE TABLE Partido (
        codigo      NUMBER PRIMARY KEY,
        fase        VARCHAR2(50) NOT NULL,
        fecha       DATE         NOT NULL,
        hora        VARCHAR2(10) NOT NULL,
        cod_estadio NUMBER       NOT NULL,
        FOREIGN KEY (cod_estadio) REFERENCES Estadio(codigo)
    )""",
    """CREATE TABLE Persona (
        codigo           NUMBER PRIMARY KEY,
        nombre           VARCHAR2(100) NOT NULL,
        nacionalidad     VARCHAR2(100),
        fecha_nacimiento DATE,
        tipo_persona     VARCHAR2(20)  NOT NULL,
        cod_seleccion    NUMBER        NOT NULL,
        CONSTRAINT ck_tipo_persona CHECK (tipo_persona IN ('JUGADOR','DIRECTOR_TECNICO')),
        FOREIGN KEY (cod_seleccion) REFERENCES Seleccion(codigo)
    )""",
    """CREATE TABLE Jugador (
        cod_persona  NUMBER PRIMARY KEY,
        estatura     NUMBER(5,2),
        peso         NUMBER(5,2),
        valor        NUMBER(15,2),
        cod_posicion NUMBER,
        FOREIGN KEY (cod_persona)  REFERENCES Persona(codigo),
        FOREIGN KEY (cod_posicion) REFERENCES Posicion(codigo)
    )""",
    """CREATE TABLE Director_Tecnico (
        cod_persona NUMBER PRIMARY KEY,
        experiencia NUMBER,
        licencia    VARCHAR2(50),
        FOREIGN KEY (cod_persona) REFERENCES Persona(codigo)
    )""",
    """CREATE TABLE Participacion (
        cod_seleccion NUMBER NOT NULL,
        cod_partido   NUMBER NOT NULL,
        goles         NUMBER DEFAULT 0,
        PRIMARY KEY (cod_seleccion, cod_partido),
        FOREIGN KEY (cod_seleccion) REFERENCES Seleccion(codigo),
        FOREIGN KEY (cod_partido)   REFERENCES Partido(codigo)
    )"""
]

INSERTS = [
    # Usuarios
    "INSERT INTO Usuario VALUES (1, 'admin',    'admin123',    'ADMINISTRADOR')",
    "INSERT INTO Usuario VALUES (2, 'user',     'user123',     'TRADICIONAL')",
    "INSERT INTO Usuario VALUES (3, 'invitado', 'invitado123', 'ESPORADICO')",
    # Ciudades del Mundial 2026
    "INSERT INTO Ciudad VALUES (1,  'Nueva York/NJ',   'USA')",
    "INSERT INTO Ciudad VALUES (2,  'Los Ángeles',     'USA')",
    "INSERT INTO Ciudad VALUES (3,  'Miami',           'USA')",
    "INSERT INTO Ciudad VALUES (4,  'Dallas',          'USA')",
    "INSERT INTO Ciudad VALUES (5,  'San Francisco',   'USA')",
    "INSERT INTO Ciudad VALUES (6,  'Seattle',         'USA')",
    "INSERT INTO Ciudad VALUES (7,  'Boston',          'USA')",
    "INSERT INTO Ciudad VALUES (8,  'Atlanta',         'USA')",
    "INSERT INTO Ciudad VALUES (9,  'Kansas City',     'USA')",
    "INSERT INTO Ciudad VALUES (10, 'Guadalajara',     'México')",
    "INSERT INTO Ciudad VALUES (11, 'Ciudad de México','México')",
    "INSERT INTO Ciudad VALUES (12, 'Monterrey',       'México')",
    "INSERT INTO Ciudad VALUES (13, 'Toronto',         'Canadá')",
    "INSERT INTO Ciudad VALUES (14, 'Vancouver',       'Canadá')",
    # Confederaciones
    "INSERT INTO Confederacion VALUES (1, 'CONMEBOL')",
    "INSERT INTO Confederacion VALUES (2, 'UEFA')",
    "INSERT INTO Confederacion VALUES (3, 'CONCACAF')",
    "INSERT INTO Confederacion VALUES (4, 'CAF')",
    "INSERT INTO Confederacion VALUES (5, 'AFC')",
    "INSERT INTO Confederacion VALUES (6, 'OFC')",
    # Posiciones
    "INSERT INTO Posicion VALUES (1, 'Portero')",
    "INSERT INTO Posicion VALUES (2, 'Defensa')",
    "INSERT INTO Posicion VALUES (3, 'Centrocampista')",
    "INSERT INTO Posicion VALUES (4, 'Delantero')",
    # 12 Grupos del Mundial 2026
    "INSERT INTO Grupo VALUES (1, 'A')", "INSERT INTO Grupo VALUES (2, 'B')",
    "INSERT INTO Grupo VALUES (3, 'C')", "INSERT INTO Grupo VALUES (4, 'D')",
    "INSERT INTO Grupo VALUES (5, 'E')", "INSERT INTO Grupo VALUES (6, 'F')",
    "INSERT INTO Grupo VALUES (7, 'G')", "INSERT INTO Grupo VALUES (8, 'H')",
    "INSERT INTO Grupo VALUES (9, 'I')", "INSERT INTO Grupo VALUES (10,'J')",
    "INSERT INTO Grupo VALUES (11,'K')", "INSERT INTO Grupo VALUES (12,'L')",
    # Estadios (14 sedes del Mundial 2026)
    "INSERT INTO Estadio VALUES (1,  'MetLife Stadium',      82500, 1)",
    "INSERT INTO Estadio VALUES (2,  'SoFi Stadium',         70240, 2)",
    "INSERT INTO Estadio VALUES (3,  'Hard Rock Stadium',    65000, 3)",
    "INSERT INTO Estadio VALUES (4,  'AT&T Stadium',         80000, 4)",
    "INSERT INTO Estadio VALUES (5,  'Levi''s Stadium',      68500, 5)",
    "INSERT INTO Estadio VALUES (6,  'Lumen Field',          68740, 6)",
    "INSERT INTO Estadio VALUES (7,  'Gillette Stadium',     65878, 7)",
    "INSERT INTO Estadio VALUES (8,  'Mercedes-Benz Stadium',71000, 8)",
    "INSERT INTO Estadio VALUES (9,  'Arrowhead Stadium',    76416, 9)",
    "INSERT INTO Estadio VALUES (10, 'Estadio Akron',        49850, 10)",
    "INSERT INTO Estadio VALUES (11, 'Estadio Azteca',       87523, 11)",
    "INSERT INTO Estadio VALUES (12, 'Estadio BBVA',         53500, 12)",
    "INSERT INTO Estadio VALUES (13, 'BMO Field',            30000, 13)",
    "INSERT INTO Estadio VALUES (14, 'BC Place',             54500, 14)",
    # Selecciones de ejemplo
    "INSERT INTO Seleccion (codigo,nombre,descripcion,cod_confederacion,cod_grupo) VALUES (1,'Argentina','La Albiceleste',1,3)",
    "INSERT INTO Seleccion (codigo,nombre,descripcion,cod_confederacion,cod_grupo) VALUES (2,'Francia','Les Bleus',2,4)",
    "INSERT INTO Seleccion (codigo,nombre,descripcion,cod_confederacion,cod_grupo) VALUES (3,'México','El Tri',3,3)",
    "INSERT INTO Seleccion (codigo,nombre,descripcion,cod_confederacion,cod_grupo) VALUES (4,'Brasil','A Seleção',1,1)",
    "INSERT INTO Seleccion (codigo,nombre,descripcion,cod_confederacion,cod_grupo) VALUES (5,'Alemania','Die Mannschaft',2,1)",
    "INSERT INTO Seleccion (codigo,nombre,descripcion,cod_confederacion,cod_grupo) VALUES (6,'USA','The Stars and Stripes',3,2)",
    # Partidos de ejemplo
    "INSERT INTO Partido VALUES (1, 'Fase de Grupos', TO_DATE('11/06/2026','DD/MM/YYYY'), '18:00', 11)",
    "INSERT INTO Partido VALUES (2, 'Fase de Grupos', TO_DATE('12/06/2026','DD/MM/YYYY'), '15:00', 1)",
    "INSERT INTO Partido VALUES (3, 'Fase de Grupos', TO_DATE('13/06/2026','DD/MM/YYYY'), '12:00', 4)",
    "INSERT INTO Partido VALUES (4, 'Final',          TO_DATE('19/07/2026','DD/MM/YYYY'), '17:00', 1)",
    # Personas: Jugadores de Argentina
    "INSERT INTO Persona VALUES (1, 'Lionel Messi',      'Argentina', TO_DATE('24/06/1987','DD/MM/YYYY'), 'JUGADOR', 1)",
    "INSERT INTO Persona VALUES (2, 'Emiliano Martínez', 'Argentina', TO_DATE('02/09/1992','DD/MM/YYYY'), 'JUGADOR', 1)",
    "INSERT INTO Persona VALUES (3, 'Rodrigo De Paul',   'Argentina', TO_DATE('24/05/1994','DD/MM/YYYY'), 'JUGADOR', 1)",
    # Personas: Jugadores de Francia
    "INSERT INTO Persona VALUES (4, 'Kylian Mbappé',     'Francia',   TO_DATE('20/12/1998','DD/MM/YYYY'), 'JUGADOR', 2)",
    "INSERT INTO Persona VALUES (5, 'Antoine Griezmann', 'Francia',   TO_DATE('21/03/1991','DD/MM/YYYY'), 'JUGADOR', 2)",
    # Personas: Jugadores de México
    "INSERT INTO Persona VALUES (6, 'Guillermo Ochoa',   'México',    TO_DATE('13/07/1985','DD/MM/YYYY'), 'JUGADOR', 3)",
    "INSERT INTO Persona VALUES (7, 'Hirving Lozano',    'México',    TO_DATE('30/07/1995','DD/MM/YYYY'), 'JUGADOR', 3)",
    # Personas: Jugadores de USA
    "INSERT INTO Persona VALUES (8, 'Christian Pulisic', 'USA',       TO_DATE('18/09/1998','DD/MM/YYYY'), 'JUGADOR', 6)",
    "INSERT INTO Persona VALUES (9, 'Tyler Adams',       'USA',       TO_DATE('27/02/1999','DD/MM/YYYY'), 'JUGADOR', 6)",
    # Directores Técnicos
    "INSERT INTO Persona VALUES (10,'Lionel Scaloni',    'Argentina', TO_DATE('16/05/1978','DD/MM/YYYY'), 'DIRECTOR_TECNICO', 1)",
    "INSERT INTO Persona VALUES (11,'Didier Deschamps',  'Francia',   TO_DATE('15/10/1968','DD/MM/YYYY'), 'DIRECTOR_TECNICO', 2)",
    "INSERT INTO Persona VALUES (12,'Javier Aguirre',    'México',    TO_DATE('01/12/1958','DD/MM/YYYY'), 'DIRECTOR_TECNICO', 3)",
    # Datos de Jugadores
    "INSERT INTO Jugador VALUES (1, 1.70, 72,  50000000, 4)",
    "INSERT INTO Jugador VALUES (2, 1.95, 88,  30000000, 1)",
    "INSERT INTO Jugador VALUES (3, 1.80, 79,  40000000, 3)",
    "INSERT INTO Jugador VALUES (4, 1.78, 73, 180000000, 4)",
    "INSERT INTO Jugador VALUES (5, 1.76, 72,  70000000, 4)",
    "INSERT INTO Jugador VALUES (6, 1.83, 78,  10000000, 1)",
    "INSERT INTO Jugador VALUES (7, 1.73, 70,  35000000, 4)",
    "INSERT INTO Jugador VALUES (8, 1.77, 76,  65000000, 4)",
    "INSERT INTO Jugador VALUES (9, 1.75, 68,  25000000, 3)",
    # Datos de Directores Técnicos
    "INSERT INTO Director_Tecnico VALUES (10, 7,  'Licencia PRO FIFA')",
    "INSERT INTO Director_Tecnico VALUES (11, 15, 'Licencia PRO UEFA')",
    "INSERT INTO Director_Tecnico VALUES (12, 12, 'Licencia PRO CONCACAF')",
    # Participaciones
    "INSERT INTO Participacion VALUES (1, 1, 2)",  # Argentina en Partido 1
    "INSERT INTO Participacion VALUES (3, 1, 0)",  # México en Partido 1
    "INSERT INTO Participacion VALUES (4, 2, 1)",  # Brasil en Partido 2
    "INSERT INTO Participacion VALUES (5, 2, 1)",  # Alemania en Partido 2
    "INSERT INTO Participacion VALUES (1, 4, 3)",  # Argentina en Final
    "INSERT INTO Participacion VALUES (2, 4, 3)",  # Francia en Final
]

def execute_script():
    try:
        conn = oracledb.connect(user=USER, password=PWD, dsn=DSN)
        cur  = conn.cursor()

        print("1/3 - Eliminando tablas existentes...")
        for t in DROP_ORDER:
            try:
                cur.execute(f"DROP TABLE {t} CASCADE CONSTRAINTS")
                print(f"   ✓ {t} eliminada")
            except oracledb.DatabaseError as e:
                err, = e.args
                if err.code == 942:  # tabla no existe
                    pass
                else:
                    print(f"   ✗ {t}: {e}")

        print("\n2/3 - Creando tablas...")
        for sql in CREATIONS:
            table_name = sql.split("TABLE")[1].split("(")[0].strip()
            cur.execute(sql)
            print(f"   ✓ {table_name}")

        print("\n3/3 - Insertando datos...")
        for sql in INSERTS:
            cur.execute(sql)
        conn.commit()
        
        cur.close()
        conn.close()
        print("\n✅ ¡Base de datos inicializada exitosamente con datos de prueba!")

    except Exception as e:
        print(f"\n❌ Error: {e}")

if __name__ == '__main__':
    execute_script()
