import oracledb

def execute_script():
    try:
        # Conexión directa con las credenciales que sabemos que te funcionan
        connection = oracledb.connect(user="SYSTEM", password="ORLO", dsn="localhost/xe")
        cursor = connection.cursor()
        
        # Lista de instrucciones SQL
        sql_commands = [
            "CREATE TABLE Ciudad (codigo NUMBER PRIMARY KEY, nombre VARCHAR2(100), pais VARCHAR2(100))",
            "CREATE TABLE Confederacion (codigo NUMBER PRIMARY KEY, nombre VARCHAR2(100))",
            "CREATE TABLE Posicion (codigo NUMBER PRIMARY KEY, nombre VARCHAR2(50))",
            "CREATE TABLE Usuario (codigo NUMBER PRIMARY KEY, nombre_usuario VARCHAR2(50) UNIQUE, contrasena VARCHAR2(100), tipo_usuario VARCHAR2(20))",
            "CREATE TABLE Estadio (codigo NUMBER PRIMARY KEY, nombre VARCHAR2(100), capacidad NUMBER, cod_ciudad NUMBER, FOREIGN KEY (cod_ciudad) REFERENCES Ciudad(codigo))",
            "CREATE TABLE Seleccion (codigo NUMBER PRIMARY KEY, nombre VARCHAR2(100), descripcion VARCHAR2(255), escudo BLOB, cod_confederacion NUMBER, FOREIGN KEY (cod_confederacion) REFERENCES Confederacion(codigo))",
            "CREATE TABLE Bitacora (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, cod_usuario NUMBER, fecha_entrada TIMESTAMP, fecha_salida TIMESTAMP, FOREIGN KEY (cod_usuario) REFERENCES Usuario(codigo))",
            "CREATE TABLE Partido (codigo NUMBER PRIMARY KEY, fecha DATE, hora VARCHAR2(10), cod_estadio NUMBER, FOREIGN KEY (cod_estadio) REFERENCES Estadio(codigo))",
            "CREATE TABLE Persona (codigo NUMBER PRIMARY KEY, nombre VARCHAR2(100), nacionalidad VARCHAR2(100), fecha_nacimiento DATE, tipo_persona VARCHAR2(20), cod_seleccion NUMBER, FOREIGN KEY (cod_seleccion) REFERENCES Seleccion(codigo))",
            "CREATE TABLE Jugador (cod_persona NUMBER PRIMARY KEY, estatura NUMBER(5,2), peso NUMBER(5,2), valor NUMBER(15,2), cod_posicion NUMBER, FOREIGN KEY (cod_persona) REFERENCES Persona(codigo), FOREIGN KEY (cod_posicion) REFERENCES Posicion(codigo))",
            "CREATE TABLE Director_Tecnico (cod_persona NUMBER PRIMARY KEY, experiencia NUMBER, licencia VARCHAR2(50), FOREIGN KEY (cod_persona) REFERENCES Persona(codigo))",
            "CREATE TABLE Participacion (cod_seleccion NUMBER, cod_partido NUMBER, goles NUMBER, PRIMARY KEY (cod_seleccion, cod_partido), FOREIGN KEY (cod_seleccion) REFERENCES Seleccion(codigo), FOREIGN KEY (cod_partido) REFERENCES Partido(codigo))",
            "INSERT INTO Usuario (codigo, nombre_usuario, contrasena, tipo_usuario) VALUES (1, 'admin', 'admin123', 'ADMINISTRADOR')"
        ]
        
        for command in sql_commands:
            try:
                cursor.execute(command)
                print("Ejecutado correctamente:", command[:30] + "...")
            except oracledb.DatabaseError as e:
                error, = e.args
                # Ignorar error si la tabla ya existe (ORA-00955)
                if error.code == 955 or error.code == 1:
                    print("La tabla/registro ya existe:", command[:30] + "...")
                else:
                    print(f"Error al ejecutar: {command[:30]}... Error: {e}")
        
        connection.commit()
        cursor.close()
        connection.close()
        print("\n¡Base de datos inicializada correctamente!")
        
    except Exception as e:
        print(f"Error general de conexión: {e}")

if __name__ == '__main__':
    execute_script()
