-- TABLAS INDEPENDIENTES
CREATE TABLE Ciudad (
    codigo NUMBER PRIMARY KEY,
    nombre VARCHAR2(100),
    pais VARCHAR2(100)
);

CREATE TABLE Confederacion (
    codigo NUMBER PRIMARY KEY,
    nombre VARCHAR2(100)
);

CREATE TABLE Posicion (
    codigo NUMBER PRIMARY KEY,
    nombre VARCHAR2(50)
);

CREATE TABLE Usuario (
    codigo NUMBER PRIMARY KEY,
    nombre_usuario VARCHAR2(50) UNIQUE,
    contrasena VARCHAR2(100),
    tipo_usuario VARCHAR2(20) -- Puede ser: 'ADMINISTRADOR', 'TRADICIONAL', 'ESPORADICO'
);

-- TABLAS DEPENDIENTES NIVEL 1
CREATE TABLE Estadio (
    codigo NUMBER PRIMARY KEY,
    nombre VARCHAR2(100),
    capacidad NUMBER,
    cod_ciudad NUMBER,
    FOREIGN KEY (cod_ciudad) REFERENCES Ciudad(codigo)
);

CREATE TABLE Seleccion (
    codigo NUMBER PRIMARY KEY,
    nombre VARCHAR2(100),
    descripcion VARCHAR2(255),
    escudo BLOB, -- Para guardar la imagen del escudo
    cod_confederacion NUMBER,
    FOREIGN KEY (cod_confederacion) REFERENCES Confederacion(codigo)
);

CREATE TABLE Bitacora (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_usuario NUMBER,
    fecha_entrada TIMESTAMP,
    fecha_salida TIMESTAMP,
    FOREIGN KEY (cod_usuario) REFERENCES Usuario(codigo)
);

-- TABLAS DEPENDIENTES NIVEL 2
CREATE TABLE Partido (
    codigo NUMBER PRIMARY KEY,
    fecha DATE,
    hora VARCHAR2(10),
    cod_estadio NUMBER,
    FOREIGN KEY (cod_estadio) REFERENCES Estadio(codigo)
);

CREATE TABLE Persona (
    codigo NUMBER PRIMARY KEY,
    nombre VARCHAR2(100),
    nacionalidad VARCHAR2(100),
    fecha_nacimiento DATE,
    tipo_persona VARCHAR2(20), -- 'JUGADOR' o 'DIRECTOR_TECNICO'
    cod_seleccion NUMBER,
    FOREIGN KEY (cod_seleccion) REFERENCES Seleccion(codigo)
);

-- TABLAS DEPENDIENTES NIVEL 3 (RELACIONADAS A PERSONA O PARTIDO)
CREATE TABLE Jugador (
    cod_persona NUMBER PRIMARY KEY,
    estatura NUMBER(5,2),
    peso NUMBER(5,2),
    valor NUMBER(15,2),
    cod_posicion NUMBER,
    FOREIGN KEY (cod_persona) REFERENCES Persona(codigo),
    FOREIGN KEY (cod_posicion) REFERENCES Posicion(codigo)
);

CREATE TABLE Director_Tecnico (
    cod_persona NUMBER PRIMARY KEY,
    experiencia NUMBER, -- años de experiencia
    licencia VARCHAR2(50),
    FOREIGN KEY (cod_persona) REFERENCES Persona(codigo)
);

CREATE TABLE Participacion (
    cod_seleccion NUMBER,
    cod_partido NUMBER,
    goles NUMBER,
    PRIMARY KEY (cod_seleccion, cod_partido),
    FOREIGN KEY (cod_seleccion) REFERENCES Seleccion(codigo),
    FOREIGN KEY (cod_partido) REFERENCES Partido(codigo)
);

-- INSERTAR UN ADMINISTRADOR POR DEFECTO PARA PODER INICIAR SESIÓN
INSERT INTO Usuario (codigo, nombre_usuario, contrasena, tipo_usuario) 
VALUES (1, 'admin', 'admin123', 'ADMINISTRADOR');
COMMIT;
