-- ============================================================
-- SISTEMA MUNDIAL DE FÚTBOL 2026 - ESQUEMA COMPLETO
-- ============================================================

-- NIVEL 0: Tablas sin dependencias
CREATE TABLE Ciudad (
    codigo   NUMBER PRIMARY KEY,
    nombre   VARCHAR2(100) NOT NULL,
    pais     VARCHAR2(100) NOT NULL  -- 'México', 'USA', 'Canadá'
);

CREATE TABLE Confederacion (
    codigo NUMBER PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL
);

CREATE TABLE Posicion (
    codigo NUMBER PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL  -- 'Portero','Defensa','Centrocampista','Delantero'
);

CREATE TABLE Usuario (
    codigo         NUMBER PRIMARY KEY,
    nombre_usuario VARCHAR2(50)  NOT NULL UNIQUE,
    contrasena     VARCHAR2(100) NOT NULL,
    tipo_usuario   VARCHAR2(20)  NOT NULL
        CHECK (tipo_usuario IN ('ADMINISTRADOR','TRADICIONAL','ESPORADICO'))
);

-- NIVEL 1: Dependen de NIVEL 0
CREATE TABLE Estadio (
    codigo      NUMBER PRIMARY KEY,
    nombre      VARCHAR2(100) NOT NULL,
    capacidad   NUMBER        NOT NULL,
    cod_ciudad  NUMBER        NOT NULL,
    FOREIGN KEY (cod_ciudad) REFERENCES Ciudad(codigo)
);

CREATE TABLE Grupo (
    codigo  NUMBER PRIMARY KEY,
    letra   VARCHAR2(1) NOT NULL UNIQUE  -- 'A'..'L' (12 grupos en 2026)
);

CREATE TABLE Seleccion (
    codigo           NUMBER PRIMARY KEY,
    nombre           VARCHAR2(100) NOT NULL,
    descripcion      VARCHAR2(255),
    escudo           BLOB,
    cod_confederacion NUMBER NOT NULL,
    cod_grupo         NUMBER,
    FOREIGN KEY (cod_confederacion) REFERENCES Confederacion(codigo),
    FOREIGN KEY (cod_grupo)         REFERENCES Grupo(codigo)
);

CREATE TABLE Bitacora (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_usuario   NUMBER NOT NULL,
    fecha_entrada TIMESTAMP NOT NULL,
    fecha_salida  TIMESTAMP,
    FOREIGN KEY (cod_usuario) REFERENCES Usuario(codigo)
);

-- NIVEL 2: Dependen de NIVEL 1
CREATE TABLE Partido (
    codigo      NUMBER PRIMARY KEY,
    fase        VARCHAR2(50) NOT NULL,  -- 'Fase de Grupos','Octavos de Final','Cuartos','Semifinal','Final'
    fecha       DATE         NOT NULL,
    hora        VARCHAR2(10) NOT NULL,
    cod_estadio NUMBER       NOT NULL,
    FOREIGN KEY (cod_estadio) REFERENCES Estadio(codigo)
);

CREATE TABLE Persona (
    codigo           NUMBER PRIMARY KEY,
    nombre           VARCHAR2(100) NOT NULL,
    nacionalidad     VARCHAR2(100),
    fecha_nacimiento DATE,
    tipo_persona     VARCHAR2(20)  NOT NULL
        CHECK (tipo_persona IN ('JUGADOR','DIRECTOR_TECNICO')),
    cod_seleccion    NUMBER        NOT NULL,
    FOREIGN KEY (cod_seleccion) REFERENCES Seleccion(codigo)
);

-- NIVEL 3: Dependen de NIVEL 2
CREATE TABLE Jugador (
    cod_persona  NUMBER PRIMARY KEY,
    estatura     NUMBER(5,2),   -- en metros  (ej: 1.75)
    peso         NUMBER(5,2),   -- en kg
    valor        NUMBER(15,2),  -- en USD
    cod_posicion NUMBER,
    FOREIGN KEY (cod_persona)  REFERENCES Persona(codigo),
    FOREIGN KEY (cod_posicion) REFERENCES Posicion(codigo)
);

CREATE TABLE Director_Tecnico (
    cod_persona  NUMBER PRIMARY KEY,
    experiencia  NUMBER,         -- años de experiencia
    licencia     VARCHAR2(50),
    FOREIGN KEY (cod_persona) REFERENCES Persona(codigo)
);

CREATE TABLE Participacion (
    cod_seleccion NUMBER NOT NULL,
    cod_partido   NUMBER NOT NULL,
    goles         NUMBER DEFAULT 0,
    PRIMARY KEY (cod_seleccion, cod_partido),
    FOREIGN KEY (cod_seleccion) REFERENCES Seleccion(codigo),
    FOREIGN KEY (cod_partido)   REFERENCES Partido(codigo)
);

-- ============================================================
-- DATOS INICIALES
-- ============================================================

-- Usuarios del sistema
INSERT INTO Usuario VALUES (1, 'admin',    'admin123',    'ADMINISTRADOR');
INSERT INTO Usuario VALUES (2, 'user',     'user123',     'TRADICIONAL');
INSERT INTO Usuario VALUES (3, 'invitado', 'invitado123', 'ESPORADICO');

-- Ciudades anfitrionas del Mundial 2026
INSERT INTO Ciudad VALUES (1,  'Nueva York/NJ',  'USA');
INSERT INTO Ciudad VALUES (2,  'Los Ángeles',    'USA');
INSERT INTO Ciudad VALUES (3,  'Miami',          'USA');
INSERT INTO Ciudad VALUES (4,  'Dallas',         'USA');
INSERT INTO Ciudad VALUES (5,  'San Francisco',  'USA');
INSERT INTO Ciudad VALUES (6,  'Seattle',        'USA');
INSERT INTO Ciudad VALUES (7,  'Boston',         'USA');
INSERT INTO Ciudad VALUES (8,  'Atlanta',        'USA');
INSERT INTO Ciudad VALUES (9,  'Kansas City',    'USA');
INSERT INTO Ciudad VALUES (10, 'Guadalajara',    'México');
INSERT INTO Ciudad VALUES (11, 'Ciudad de México','México');
INSERT INTO Ciudad VALUES (12, 'Monterrey',      'México');
INSERT INTO Ciudad VALUES (13, 'Toronto',        'Canadá');
INSERT INTO Ciudad VALUES (14, 'Vancouver',      'Canadá');

-- Confederaciones
INSERT INTO Confederacion VALUES (1, 'CONMEBOL');
INSERT INTO Confederacion VALUES (2, 'UEFA');
INSERT INTO Confederacion VALUES (3, 'CONCACAF');
INSERT INTO Confederacion VALUES (4, 'CAF');
INSERT INTO Confederacion VALUES (5, 'AFC');
INSERT INTO Confederacion VALUES (6, 'OFC');

-- Posiciones
INSERT INTO Posicion VALUES (1, 'Portero');
INSERT INTO Posicion VALUES (2, 'Defensa');
INSERT INTO Posicion VALUES (3, 'Centrocampista');
INSERT INTO Posicion VALUES (4, 'Delantero');

-- 12 Grupos del Mundial 2026
INSERT INTO Grupo VALUES (1,  'A');
INSERT INTO Grupo VALUES (2,  'B');
INSERT INTO Grupo VALUES (3,  'C');
INSERT INTO Grupo VALUES (4,  'D');
INSERT INTO Grupo VALUES (5,  'E');
INSERT INTO Grupo VALUES (6,  'F');
INSERT INTO Grupo VALUES (7,  'G');
INSERT INTO Grupo VALUES (8,  'H');
INSERT INTO Grupo VALUES (9,  'I');
INSERT INTO Grupo VALUES (10, 'J');
INSERT INTO Grupo VALUES (11, 'K');
INSERT INTO Grupo VALUES (12, 'L');

-- Estadios anfitriones
INSERT INTO Estadio VALUES (1,  'MetLife Stadium',            82500, 1);
INSERT INTO Estadio VALUES (2,  'SoFi Stadium',               70240, 2);
INSERT INTO Estadio VALUES (3,  'Hard Rock Stadium',          65000, 3);
INSERT INTO Estadio VALUES (4,  'AT&T Stadium',               80000, 4);
INSERT INTO Estadio VALUES (5,  'Levi''s Stadium',            68500, 5);
INSERT INTO Estadio VALUES (6,  'Lumen Field',                68740, 6);
INSERT INTO Estadio VALUES (7,  'Gillette Stadium',           65878, 7);
INSERT INTO Estadio VALUES (8,  'Mercedes-Benz Stadium',      71000, 8);
INSERT INTO Estadio VALUES (9,  'Arrowhead Stadium',          76416, 9);
INSERT INTO Estadio VALUES (10, 'Estadio Akron',              49850, 10);
INSERT INTO Estadio VALUES (11, 'Estadio Azteca',             87523, 11);
INSERT INTO Estadio VALUES (12, 'Estadio BBVA',               53500, 12);
INSERT INTO Estadio VALUES (13, 'BMO Field',                  30000, 13);
INSERT INTO Estadio VALUES (14, 'BC Place',                   54500, 14);

COMMIT;
