-- ============================================================
-- SISTEMA MUNDIAL DE FÚTBOL 2026 - ESQUEMA COMPLETO
-- Adaptado al diagrama ER oficial del proyecto
-- ============================================================

-- LIMPIEZA: Borrar tablas en orden correcto para evitar conflictos de FK
DROP TABLE Detalles_Partido_Seleccion CASCADE CONSTRAINTS;
DROP TABLE Participacion CASCADE CONSTRAINTS;
DROP TABLE Director_Tecnico CASCADE CONSTRAINTS;
DROP TABLE Jugador CASCADE CONSTRAINTS;
DROP TABLE Persona CASCADE CONSTRAINTS;
DROP TABLE Partido CASCADE CONSTRAINTS;
DROP TABLE Bitacora CASCADE CONSTRAINTS;
DROP TABLE Seleccion CASCADE CONSTRAINTS;
DROP TABLE Grupo CASCADE CONSTRAINTS;
DROP TABLE Estadio CASCADE CONSTRAINTS;
DROP TABLE Ciudad CASCADE CONSTRAINTS;
DROP TABLE Pais CASCADE CONSTRAINTS;
DROP TABLE Usuario CASCADE CONSTRAINTS;
DROP TABLE Posicion CASCADE CONSTRAINTS;
DROP TABLE Confederacion CASCADE CONSTRAINTS;

-- ============================================================
-- NIVEL 0: Tablas sin dependencias externas
-- ============================================================

CREATE TABLE Pais (
    codigo_pais NUMBER PRIMARY KEY,
    nombre      VARCHAR2(100) NOT NULL
);

CREATE TABLE Confederacion (
    codigo_confederacion NUMBER PRIMARY KEY,
    nombre               VARCHAR2(100) NOT NULL
);

CREATE TABLE Posicion (
    codigo_posicion NUMBER PRIMARY KEY,
    nombre          VARCHAR2(50) NOT NULL
);

CREATE TABLE Usuario (
    codigo_usuario NUMBER PRIMARY KEY,
    nombreUsuario  VARCHAR2(50)  NOT NULL UNIQUE,
    contrasena     VARCHAR2(100) NOT NULL,
    tipo_usuario   VARCHAR2(20)  NOT NULL,
    CONSTRAINT ck_tipo_usuario CHECK (tipo_usuario IN ('ADMINISTRADOR','TRADICIONAL','ESPORADICO'))
);

CREATE TABLE Grupo (
    codigo_grupo NUMBER PRIMARY KEY,
    nombre       VARCHAR2(10) NOT NULL UNIQUE
);

-- ============================================================
-- NIVEL 1: Dependen de NIVEL 0
-- ============================================================

CREATE TABLE Ciudad (
    codigo_ciudad NUMBER PRIMARY KEY,
    nombre        VARCHAR2(100) NOT NULL,
    codigo_pais   NUMBER        NOT NULL,
    FOREIGN KEY (codigo_pais) REFERENCES Pais(codigo_pais)
);

CREATE TABLE Seleccion (
    codigo_seleccion     NUMBER PRIMARY KEY,
    nombre               VARCHAR2(100) NOT NULL,
    descripcion          VARCHAR2(255),
    escudo               BLOB,
    codigo_grupo         NUMBER,
    codigo_pais          NUMBER        NOT NULL,
    codigo_confederacion NUMBER        NOT NULL,
    FOREIGN KEY (codigo_grupo)         REFERENCES Grupo(codigo_grupo),
    FOREIGN KEY (codigo_pais)          REFERENCES Pais(codigo_pais),
    FOREIGN KEY (codigo_confederacion) REFERENCES Confederacion(codigo_confederacion)
);

CREATE TABLE Bitacora (
    codigo_bitacora  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fechaHoraEntrada TIMESTAMP NOT NULL,
    fechaHoraSalida  TIMESTAMP,
    codigo_usuario   NUMBER    NOT NULL,
    FOREIGN KEY (codigo_usuario) REFERENCES Usuario(codigo_usuario)
);

-- ============================================================
-- NIVEL 2: Dependen de NIVEL 1
-- ============================================================

CREATE TABLE Estadio (
    codigo_estadio NUMBER PRIMARY KEY,
    nombre         VARCHAR2(100) NOT NULL,
    capacidad      NUMBER        NOT NULL,
    codigo_ciudad  NUMBER        NOT NULL,
    FOREIGN KEY (codigo_ciudad) REFERENCES Ciudad(codigo_ciudad)
);

CREATE TABLE Persona (
    codigo_persona   NUMBER PRIMARY KEY,
    nombre           VARCHAR2(100) NOT NULL,
    nacionalidad     VARCHAR2(100),
    fecha_nacimiento DATE
);

-- ============================================================
-- NIVEL 3: Dependen de NIVEL 2
-- ============================================================

CREATE TABLE Partido (
    codigo_partido NUMBER PRIMARY KEY,
    fecha          DATE         NOT NULL,
    hora           VARCHAR2(10) NOT NULL,
    codigo_estadio NUMBER       NOT NULL,
    codigo_grupo   NUMBER,
    FOREIGN KEY (codigo_estadio) REFERENCES Estadio(codigo_estadio),
    FOREIGN KEY (codigo_grupo)   REFERENCES Grupo(codigo_grupo)
);

CREATE TABLE Jugador (
    codigo_persona   NUMBER PRIMARY KEY,
    estatura         NUMBER(5,2),
    peso             NUMBER(5,2),
    valor            NUMBER(15,2),
    codigo_seleccion NUMBER        NOT NULL,
    codigo_posicion  NUMBER,
    FOREIGN KEY (codigo_persona)   REFERENCES Persona(codigo_persona),
    FOREIGN KEY (codigo_seleccion) REFERENCES Seleccion(codigo_seleccion),
    FOREIGN KEY (codigo_posicion)  REFERENCES Posicion(codigo_posicion)
);

CREATE TABLE Director_Tecnico (
    codigo_persona   NUMBER PRIMARY KEY,
    experiencia      NUMBER,
    licencia         VARCHAR2(50),
    codigo_seleccion NUMBER NOT NULL,
    FOREIGN KEY (codigo_persona)   REFERENCES Persona(codigo_persona),
    FOREIGN KEY (codigo_seleccion) REFERENCES Seleccion(codigo_seleccion)
);

-- ============================================================
-- NIVEL 4: Tablas de relación
-- ============================================================

CREATE TABLE Detalles_Partido_Seleccion (
    codigo_seleccion NUMBER NOT NULL,
    codigo_partido   NUMBER NOT NULL,
    goles_local      NUMBER DEFAULT 0,
    goles_visita     NUMBER DEFAULT 0,
    PRIMARY KEY (codigo_seleccion, codigo_partido),
    FOREIGN KEY (codigo_seleccion) REFERENCES Seleccion(codigo_seleccion),
    FOREIGN KEY (codigo_partido)   REFERENCES Partido(codigo_partido)
);

-- ============================================================
-- DATOS INICIALES
-- ============================================================

-- Usuarios del sistema
INSERT INTO Usuario VALUES (1, 'admin',    'admin123',    'ADMINISTRADOR');
INSERT INTO Usuario VALUES (2, 'user',     'user123',     'TRADICIONAL');
INSERT INTO Usuario VALUES (3, 'invitado', 'invitado123', 'ESPORADICO');

-- Confederaciones (las 6 oficiales de la FIFA)
INSERT INTO Confederacion VALUES (1, 'CONMEBOL');
INSERT INTO Confederacion VALUES (2, 'UEFA');
INSERT INTO Confederacion VALUES (3, 'CONCACAF');
INSERT INTO Confederacion VALUES (4, 'CAF');
INSERT INTO Confederacion VALUES (5, 'AFC');
INSERT INTO Confederacion VALUES (6, 'OFC');

-- Posiciones
INSERT INTO Posicion VALUES (1, 'Portero');
INSERT INTO Posicion VALUES (2, 'Defensa');
INSERT INTO Posicion VALUES (3, 'Centrocampista');
INSERT INTO Posicion VALUES (4, 'Delantero');

-- 12 Grupos del Mundial 2026
INSERT INTO Grupo VALUES (1,  'A');
INSERT INTO Grupo VALUES (2,  'B');
INSERT INTO Grupo VALUES (3,  'C');
INSERT INTO Grupo VALUES (4,  'D');
INSERT INTO Grupo VALUES (5,  'E');
INSERT INTO Grupo VALUES (6,  'F');
INSERT INTO Grupo VALUES (7,  'G');
INSERT INTO Grupo VALUES (8,  'H');
INSERT INTO Grupo VALUES (9,  'I');
INSERT INTO Grupo VALUES (10, 'J');
INSERT INTO Grupo VALUES (11, 'K');
INSERT INTO Grupo VALUES (12, 'L');

-- Países (anfitriones + países de las selecciones de ejemplo)
INSERT INTO Pais VALUES (1, 'USA');
INSERT INTO Pais VALUES (2, 'México');
INSERT INTO Pais VALUES (3, 'Canadá');
INSERT INTO Pais VALUES (4, 'Argentina');
INSERT INTO Pais VALUES (5, 'Francia');
INSERT INTO Pais VALUES (6, 'Brasil');
INSERT INTO Pais VALUES (7, 'Alemania');

-- Ciudades anfitrionas (referenciando código de país)
INSERT INTO Ciudad VALUES (1,  'Nueva York/NJ',    1);
INSERT INTO Ciudad VALUES (2,  'Los Ángeles',      1);
INSERT INTO Ciudad VALUES (3,  'Miami',            1);
INSERT INTO Ciudad VALUES (4,  'Dallas',           1);
INSERT INTO Ciudad VALUES (5,  'San Francisco',    1);
INSERT INTO Ciudad VALUES (6,  'Seattle',          1);
INSERT INTO Ciudad VALUES (7,  'Boston',           1);
INSERT INTO Ciudad VALUES (8,  'Atlanta',          1);
INSERT INTO Ciudad VALUES (9,  'Kansas City',      1);
INSERT INTO Ciudad VALUES (10, 'Guadalajara',      2);
INSERT INTO Ciudad VALUES (11, 'Ciudad de México', 2);
INSERT INTO Ciudad VALUES (12, 'Monterrey',        2);
INSERT INTO Ciudad VALUES (13, 'Toronto',          3);
INSERT INTO Ciudad VALUES (14, 'Vancouver',        3);

-- Estadios (14 sedes del Mundial 2026)
INSERT INTO Estadio VALUES (1,  'MetLife Stadium',       82500, 1);
INSERT INTO Estadio VALUES (2,  'SoFi Stadium',          70240, 2);
INSERT INTO Estadio VALUES (3,  'Hard Rock Stadium',     65000, 3);
INSERT INTO Estadio VALUES (4,  'AT&T Stadium',          80000, 4);
INSERT INTO Estadio VALUES (5,  'Levi''s Stadium',       68500, 5);
INSERT INTO Estadio VALUES (6,  'Lumen Field',           68740, 6);
INSERT INTO Estadio VALUES (7,  'Gillette Stadium',      65878, 7);
INSERT INTO Estadio VALUES (8,  'Mercedes-Benz Stadium', 71000, 8);
INSERT INTO Estadio VALUES (9,  'Arrowhead Stadium',     76416, 9);
INSERT INTO Estadio VALUES (10, 'Estadio Akron',         49850, 10);
INSERT INTO Estadio VALUES (11, 'Estadio Azteca',        87523, 11);
INSERT INTO Estadio VALUES (12, 'Estadio BBVA',          53500, 12);
INSERT INTO Estadio VALUES (13, 'BMO Field',             30000, 13);
INSERT INTO Estadio VALUES (14, 'BC Place',              54500, 14);

-- Selecciones de ejemplo
INSERT INTO Seleccion (codigo_seleccion, nombre, descripcion, codigo_grupo, codigo_pais, codigo_confederacion) VALUES (1, 'Argentina', 'La Albiceleste',        3, 4, 1);
INSERT INTO Seleccion (codigo_seleccion, nombre, descripcion, codigo_grupo, codigo_pais, codigo_confederacion) VALUES (2, 'Francia',   'Les Bleus',             4, 5, 2);
INSERT INTO Seleccion (codigo_seleccion, nombre, descripcion, codigo_grupo, codigo_pais, codigo_confederacion) VALUES (3, 'México',    'El Tri',                3, 2, 3);
INSERT INTO Seleccion (codigo_seleccion, nombre, descripcion, codigo_grupo, codigo_pais, codigo_confederacion) VALUES (4, 'Brasil',    'A Seleção',             1, 6, 1);
INSERT INTO Seleccion (codigo_seleccion, nombre, descripcion, codigo_grupo, codigo_pais, codigo_confederacion) VALUES (5, 'Alemania',  'Die Mannschaft',        1, 7, 2);
INSERT INTO Seleccion (codigo_seleccion, nombre, descripcion, codigo_grupo, codigo_pais, codigo_confederacion) VALUES (6, 'USA',       'The Stars and Stripes', 2, 1, 3);

-- Partidos de ejemplo
INSERT INTO Partido VALUES (1, TO_DATE('11/06/2026','DD/MM/YYYY'), '18:00', 11, 3);
INSERT INTO Partido VALUES (2, TO_DATE('12/06/2026','DD/MM/YYYY'), '15:00',  1, 1);
INSERT INTO Partido VALUES (3, TO_DATE('13/06/2026','DD/MM/YYYY'), '12:00',  4, 1);
INSERT INTO Partido VALUES (4, TO_DATE('19/07/2026','DD/MM/YYYY'), '17:00',  1, NULL);

-- Personas
INSERT INTO Persona VALUES (1,  'Lionel Messi',      'Argentina', TO_DATE('24/06/1987','DD/MM/YYYY'));
INSERT INTO Persona VALUES (2,  'Emiliano Martínez', 'Argentina', TO_DATE('02/09/1992','DD/MM/YYYY'));
INSERT INTO Persona VALUES (3,  'Rodrigo De Paul',   'Argentina', TO_DATE('24/05/1994','DD/MM/YYYY'));
INSERT INTO Persona VALUES (4,  'Kylian Mbappé',     'Francia',   TO_DATE('20/12/1998','DD/MM/YYYY'));
INSERT INTO Persona VALUES (5,  'Antoine Griezmann', 'Francia',   TO_DATE('21/03/1991','DD/MM/YYYY'));
INSERT INTO Persona VALUES (6,  'Guillermo Ochoa',   'México',    TO_DATE('13/07/1985','DD/MM/YYYY'));
INSERT INTO Persona VALUES (7,  'Hirving Lozano',    'México',    TO_DATE('30/07/1995','DD/MM/YYYY'));
INSERT INTO Persona VALUES (8,  'Christian Pulisic', 'USA',       TO_DATE('18/09/1998','DD/MM/YYYY'));
INSERT INTO Persona VALUES (9,  'Tyler Adams',       'USA',       TO_DATE('27/02/1999','DD/MM/YYYY'));
INSERT INTO Persona VALUES (10, 'Lionel Scaloni',    'Argentina', TO_DATE('16/05/1978','DD/MM/YYYY'));
INSERT INTO Persona VALUES (11, 'Didier Deschamps',  'Francia',   TO_DATE('15/10/1968','DD/MM/YYYY'));
INSERT INTO Persona VALUES (12, 'Javier Aguirre',    'México',    TO_DATE('01/12/1958','DD/MM/YYYY'));

-- Jugadores (codigo_persona, estatura, peso, valor, codigo_seleccion, codigo_posicion)
INSERT INTO Jugador VALUES (1, 1.70, 72,  50000000, 1, 4);
INSERT INTO Jugador VALUES (2, 1.95, 88,  30000000, 1, 1);
INSERT INTO Jugador VALUES (3, 1.80, 79,  40000000, 1, 3);
INSERT INTO Jugador VALUES (4, 1.78, 73, 180000000, 2, 4);
INSERT INTO Jugador VALUES (5, 1.76, 72,  70000000, 2, 4);
INSERT INTO Jugador VALUES (6, 1.83, 78,  10000000, 3, 1);
INSERT INTO Jugador VALUES (7, 1.73, 70,  35000000, 3, 4);
INSERT INTO Jugador VALUES (8, 1.77, 76,  65000000, 6, 4);
INSERT INTO Jugador VALUES (9, 1.75, 68,  25000000, 6, 3);

-- Directores Técnicos (codigo_persona, experiencia, licencia, codigo_seleccion)
INSERT INTO Director_Tecnico VALUES (10, 7,  'Licencia PRO',  1);
INSERT INTO Director_Tecnico VALUES (11, 15, 'Licencia PRO',  2);
INSERT INTO Director_Tecnico VALUES (12, 12, 'Licencia PRO',  3);

-- Detalles de partidos (codigo_seleccion, codigo_partido, goles_local, goles_visita)
INSERT INTO Detalles_Partido_Seleccion VALUES (1, 1, 2, 0);
INSERT INTO Detalles_Partido_Seleccion VALUES (3, 1, 0, 2);
INSERT INTO Detalles_Partido_Seleccion VALUES (4, 2, 1, 1);
INSERT INTO Detalles_Partido_Seleccion VALUES (5, 2, 1, 1);
INSERT INTO Detalles_Partido_Seleccion VALUES (1, 4, 3, 3);
INSERT INTO Detalles_Partido_Seleccion VALUES (2, 4, 3, 3);

COMMIT;
